/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.main.java.com.test;

import java.util.ArrayList;
import java.util.Iterator;

public class App {
  
    public static void main(String[] args) {
       
    	ArrayList<String> al=new ArrayList<>();
    	
    	al.add("name");
    	al.add("name");
    	al.add("name");
    	al.add("name");
    	al.add("name");
    	al.add("name");
    	al.add("name");
    	
    	
    	Iterator<String> i=al.iterator();
    	
    	while(i.hasNext()){
    		System.out.println(i.next());
    	}
    	
    }
}
